version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/cloud189
    id: "cloud189"
    binary: cloud189
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - arm
      - arm64
      - amd64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm

archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: gowsp
    name: cloud189